#!/bin/zsh

submit-src-changes() {
    if [ -z "$2" ]; then
        echo "Usage: submit-src-changes <primer-name> <branch-name>"
        return 1
    fi
cd "$(dirname "$0")/.." || exit
    git add -A
    git commit -m "add $1"
    git push -u origin "$2"
}